{% set name = "editabletuple" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/editabletuple-{{ version }}.tar.gz
  sha256: d74c1d162a18204bd8c95ad1130b959e322988afc1eacaf2adb5fe9a99bf3555

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - editabletuple
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mark-summerfield/editabletuple
  summary: Provides the editabletuple function for creating classes with a fixed sequence of fields, similar to a namedtuple, except editable
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
