{% set name = "editabletuple" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/editabletuple-{{ version }}.tar.gz
  sha256: 033cd9cfb8eac81a722dcb545dd509d82b26337d7f087cfa860866dfc3ca0fee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - editabletuple
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mark-summerfield/editabletuple
  summary: Provides the editabletuple function for creating classes with a fixed sequence of fields, similar to a namedtuple, except editable
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
